StaticWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls'))
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:album_id>/', views.detail, name='details'),
    path('about/', views.about, name='about'),
]

pages/models.py
from django.db import models


# Create your models here.
class Albums(models.Model):

    name = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    logo = models.CharField(max_length=300, default="https://images.pexels.com/photos/68147/waterfall-thac-dray-nur-buon-me-thuot-daklak-68147.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500")

    def __str__(self):
        return self.name + "-" + self.description


class Images(models.Model):

    albums = models.ForeignKey(Albums, on_delete=models.CASCADE)
    image_caption = models.CharField(max_length=250)
    image_link = models.CharField(max_length=250)

    def __str__(self):
        return self.image_caption

pages/views.py
from django.shortcuts import render, get_object_or_404
from .models import Albums
from datetime import datetime


# Create your views here.
def index(request):
    all_albums = Albums.objects.all()
    context = {'all_albums': all_albums}
    return render(request, 'index.html', context=context)


def detail(request, album_id):
    album = get_object_or_404(Albums, pk=album_id)
    return render(request, "details.html", {'album':album})


def about(request):
    return render(request, 'about.html')

templates/about.html
{% extends 'base.html' %}

templates/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<link>
    <meta charset="UTF-8">
    <title>{% block title %}christine{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

    <link rel="stylesheet"  type="text/css" href="{% static "styles.css" %}" >

<header>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand navbar-left" href="{% url 'index' %}">Music Albums</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav ">
                    <li class=""><a href="{% url 'index' %}"><span class="glyphicon glyphicon-camera" aria-hidden="true"></span>&nbsp; Albums</a></li>
                    <li class=""><a href="{% url 'about' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; About</a></li>
                </ul>
                <form class="navbar-form navbar-right" role="search" method="get" action="{% url 'index' %}">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                    </div>
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
            </div>

        </div>
   </nav>

</header>



<body>

{% block body %}



{% endblock %}

  <footer>

<div class="jumbotron ">


  <div class="container">
     <div class="follow" id="contacts">
                <h1><span>Follow Me</span></h1>
                <div>
                <table><tr><td>

                    <a href="" target="_blank">
                        <img alt="LinkedIn" src="https://cdn2.iconfinder.com/data/icons/black-white-social-media/32/linked_in_online_social_media-128.png" />
                    </a><br/>LINKED IN</td><td>
                    <a href="" target="_blank">
                        <img alt="Facebook" src="https://cdn3.iconfinder.com/data/icons/free-social-icons/67/facebook_circle_black-512.png" />
                    </a><br/>Facebook</td><td>
                    <a href="" target="_blank">
                        <img alt="Instagram" src="https://cdn4.iconfinder.com/data/icons/picons-social/57/38-instagram-3-512.png"/>
                    </a><br/>Instagram</td><td>
                  </table>
                </div>
            </div>
            </div>
    </div>
 </footer>

<div class="container">
    <div class="copyright">
              &copy; 2019 Hezekiah. All rights reserved.
      </div>
    </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>

templates/details.html
{% extends "base.html" %}

{% block body %}


        {% for image in album.images_set.all %}
    <div class="container">
        <div class="row">
             <div class="col-lg-6">
                <div class="thumbnail">
                   <img src="{{ image.image_link }}" alt="images">
                <div class="caption">
                    <h3>{{ image.image_caption }}</h3>
                    <figcaption class="figure-caption text-right">Created by Hezekiah.</figcaption>
                </div>
             </div>
          </div>
      </div>
    </div>

    {% endfor %}
{% endblock body %}

templates/index.html
{% extends "base.html" %}

{% block body %}
{% if all_albums %}
    {% for album in all_albums %}
    <div class="container">
        <div class="row">
             <div class="col-lg-6">
                <div class="thumbnail">
                   <a href="{{ album.id }}"> <img src="{{ album.logo }}" alt="images" width="300" height="300"></a>
                <div class="caption">
                    <h3>{{ album.album_name }}</h3>
                    <figcaption class="figure-caption text-right">Created by Hezekiah</figcaption>
                </div>
             </div>
          </div>
      </div>
    </div>
    {% endfor %}
{% endif %}
{% endblock body %}